# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Files\email_distribution.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_distributionLists(object):
    def setupUi(self, distributionLists):
        distributionLists.setObjectName("distributionLists")
        distributionLists.resize(323, 388)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"\\172.16.33.31\collectone\COLLECTOR RESOURCES\KPI Tracker\cmredb\Meduit_logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        distributionLists.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(distributionLists)
        self.gridLayout.setObjectName("gridLayout")
        self.listBrowser = QtWidgets.QTextBrowser(distributionLists)
        self.listBrowser.setOpenExternalLinks(True)
        self.listBrowser.setObjectName("listBrowser")
        self.gridLayout.addWidget(self.listBrowser, 0, 0, 1, 1)

        self.retranslateUi(distributionLists)
        QtCore.QMetaObject.connectSlotsByName(distributionLists)

    def retranslateUi(self, distributionLists):
        _translate = QtCore.QCoreApplication.translate
        distributionLists.setWindowTitle(_translate("distributionLists", "Email Distribution Lists"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    distributionLists = QtWidgets.QWidget()
    ui = Ui_distributionLists()
    ui.setupUi(distributionLists)
    distributionLists.show()
    sys.exit(app.exec_())
