# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_managerSettings(object):
    def setupUi(self, managerSettings):
        managerSettings.setObjectName("managerSettings")
        managerSettings.resize(715, 228)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("J:/COLLECTOR RESOURCES/KPI Tracker/cmredb/Meduit_logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        managerSettings.setWindowIcon(icon)
        managerSettings.setStyleSheet("QDialog{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0.011, stop:0 rgba(255, 218, 144, 200), stop:1 rgba(129, 213, 255, 126));\n"
"}\n"
"QWidget{\n"
"    font: 11pt \"Corbel\";\n"
"    font-weight: bold;\n"
"}\n"
"QGroupBox{\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(255, 255, 255, 209), stop:0.485876 rgba(181, 207, 220, 239), stop:1 rgba(85, 199, 255, 196));\n"
"    border: 1px solid black;\n"
"    border-radius: 3px;\n"
"    margin-top: 1ex;\n"
"    padding-top: 18;\n"
"    font: 11pt \"Corbel\";\n"
"    font-weight: bold;\n"
"}\n"
"QGroupBox::title{\n"
"    background-color: rgb(195, 195, 195);\n"
"    border: 1px solid black;\n"
"    border-radius: 3px;\n"
"    padding: 2 10px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top;\n"
"    font: 11pt \"Corbel\";\n"
"    font-weight: bold;\n"
"}\n"
"QLineEdit{\n"
"    background-color: rgb(223, 223, 223);\n"
"    border: 1px solid black;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QTextEdit{\n"
"    font: 12pt \"Corbel\";\n"
"}\n"
"QStatusBar{\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton{\n"
"    border-bottom: 2px solid rgb(75, 124, 154);\n"
"    border-top: 1px solid rgb(95, 158, 195);\n"
"    border-right: 2px solid rgb(75, 124, 154);\n"
"    border-left: 1px solid rgb(95, 158, 195);\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"    padding-left: 13px;\n"
"    padding-right: 13px;\n"
"    background-color: rgb(225, 225, 225);\n"
"    font: 11pt \"Corbel\";\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton::hover{\n"
"    border-bottom: 2px solid rgb(75, 124, 154);\n"
"    border-top: 1px solid rgb(95, 158, 195);\n"
"    border-right: 2px solid rgb(75, 124, 154);\n"
"    border-left: 1px solid rgb(95, 158, 195);\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"    padding-left: 13px;\n"
"    padding-right: 13px;\n"
"    background-color: rgb(215, 215, 215);\n"
"    font: 11pt \"Corbel\";\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton::pressed{\n"
"    border-bottom: 1px solid rgb(75, 124, 154);\n"
"    border-top: 2px solid rgb(95, 158, 195);\n"
"    border-right: 1px solid rgb(75, 124, 154);\n"
"    border-left: 2px solid rgb(95, 158, 195);\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    width: 80px;\n"
"    background-color: rgb(225, 225, 225);\n"
"    font: 11pt \"Corbel\";\n"
"    font-weight: bold;\n"
"}\n"
"QComboBox{\n"
"    border-bottom: 2px solid rgb(75, 124, 154);\n"
"    border-top: 1px solid rgb(75, 124, 154);\n"
"    border-right: 1px solid rgb(75, 124, 154);\n"
"    border-left: 1px solid rgb(75, 124, 154);\n"
"    border-radius: 3px;\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"QComboBox::drop-down{\n"
"    background-color: rgb(215, 215, 215);\n"
"    border-bottom: 2px solid rgb(75, 124, 154);\n"
"    border-top: 1px solid rgb(95, 158, 195);\n"
"    border-right: 2px solid rgb(75, 124, 154);\n"
"    border-left: 1px solid rgb(95, 158, 195);\n"
"    border-radius: 3px;\n"
"    subcontrol-origin: margin;\n"
"    width: 16px;\n"
"}\n"
"QComboBox::drop-down::hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"    border-bottom: 2px solid rgb(75, 124, 154);\n"
"    border-top: 1px solid rgb(95, 158, 195);\n"
"    border-right: 2px solid rgb(75, 124, 154);\n"
"    border-left: 1px solid rgb(95, 158, 195);\n"
"    border-radius: 3px;\n"
"    subcontrol-origin: margin;\n"
"    width: 16px;\n"
"}\n"
"QComboBox::drop-down::pressed{\n"
"    background-color: rgb(215, 215, 215);\n"
"    border-bottom: 1px solid rgb(75, 124, 154);\n"
"    border-top: 2px solid rgb(95, 158, 195);\n"
"    border-right: 1px solid rgb(75, 124, 154);\n"
"    border-left: 2px solid rgb(95, 158, 195);\n"
"    border-radius: 3px;\n"
"    subcontrol-origin: margin;\n"
"    width: 16px;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/meduit/arrow.png);\n"
"    width: 14 px;\n"
"    height:14 px;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(managerSettings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.saveClose = QtWidgets.QPushButton(managerSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveClose.sizePolicy().hasHeightForWidth())
        self.saveClose.setSizePolicy(sizePolicy)
        self.saveClose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saveClose.setAutoDefault(False)
        self.saveClose.setObjectName("saveClose")
        self.gridLayout_2.addWidget(self.saveClose, 1, 2, 1, 1)
        self.closeButton = QtWidgets.QPushButton(managerSettings)
        self.closeButton.setMinimumSize(QtCore.QSize(111, 0))
        self.closeButton.setObjectName("closeButton")
        self.gridLayout_2.addWidget(self.closeButton, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(managerSettings)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("QFrame{\n"
"    border-color: rgb(0, 82, 124);\n"
"    border-style: solid;\n"
"    border-width: 1px 1px 1px 10px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}")
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkMyColl = QtWidgets.QCheckBox(self.frame_3)
        self.checkMyColl.setObjectName("checkMyColl")
        self.verticalLayout.addWidget(self.checkMyColl)
        self.checkGraphPre = QtWidgets.QCheckBox(self.frame_3)
        self.checkGraphPre.setObjectName("checkGraphPre")
        self.verticalLayout.addWidget(self.checkGraphPre)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setStyleSheet("QFrame{\n"
"    border-color: rgb(0, 82, 124);\n"
"    border-style: solid;\n"
"    border-width: 1px 1px 1px 10px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}")
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.graphPreset = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphPreset.sizePolicy().hasHeightForWidth())
        self.graphPreset.setSizePolicy(sizePolicy)
        self.graphPreset.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(255, 255, 255, 209), stop:0.485876 rgba(181, 207, 220, 239), stop:1 rgba(85, 199, 255, 196));\n"
"}")
        self.graphPreset.setObjectName("graphPreset")
        self.graphPreset.addItem("")
        self.graphPreset.addItem("")
        self.graphPreset.addItem("")
        self.horizontalLayout.addWidget(self.graphPreset)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frame_5, 0, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphData1 = QtWidgets.QComboBox(self.frame_2)
        self.graphData1.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(255, 255, 255, 209), stop:0.485876 rgba(181, 207, 220, 239), stop:1 rgba(85, 199, 255, 196));\n"
"}")
        self.graphData1.setObjectName("graphData1")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.graphData1.addItem("")
        self.verticalLayout_2.addWidget(self.graphData1)
        self.graphData3 = QtWidgets.QComboBox(self.frame_2)
        self.graphData3.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(255, 255, 255, 209), stop:0.485876 rgba(181, 207, 220, 239), stop:1 rgba(85, 199, 255, 196));\n"
"}")
        self.graphData3.setObjectName("graphData3")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.graphData3.addItem("")
        self.verticalLayout_2.addWidget(self.graphData3)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphData2 = QtWidgets.QComboBox(self.frame_4)
        self.graphData2.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(255, 255, 255, 209), stop:0.485876 rgba(181, 207, 220, 239), stop:1 rgba(85, 199, 255, 196));\n"
"}")
        self.graphData2.setObjectName("graphData2")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.graphData2.addItem("")
        self.verticalLayout_3.addWidget(self.graphData2)
        self.graphData4 = QtWidgets.QComboBox(self.frame_4)
        self.graphData4.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(255, 255, 255, 209), stop:0.485876 rgba(181, 207, 220, 239), stop:1 rgba(85, 199, 255, 196));\n"
"}")
        self.graphData4.setObjectName("graphData4")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.graphData4.addItem("")
        self.verticalLayout_3.addWidget(self.graphData4)
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 3)

        self.retranslateUi(managerSettings)
        self.graphPreset.setCurrentIndex(0)
        self.graphData1.setCurrentIndex(-1)
        self.graphData3.setCurrentIndex(-1)
        self.graphData2.setCurrentIndex(-1)
        self.graphData4.setCurrentIndex(-1)
        self.closeButton.clicked.connect(managerSettings.close)
        QtCore.QMetaObject.connectSlotsByName(managerSettings)

    def retranslateUi(self, managerSettings):
        _translate = QtCore.QCoreApplication.translate
        managerSettings.setWindowTitle(_translate("managerSettings", "Settings Menu"))
        self.saveClose.setText(_translate("managerSettings", "Save && Close"))
        self.closeButton.setText(_translate("managerSettings", "Close"))
        self.groupBox.setTitle(_translate("managerSettings", "Basic Settings"))
        self.checkMyColl.setText(_translate("managerSettings", "Load With My Collectors"))
        self.checkGraphPre.setText(_translate("managerSettings", "Use Graph Presets"))
        self.graphPreset.setItemText(0, _translate("managerSettings", "Graph Preset 1"))
        self.graphPreset.setItemText(1, _translate("managerSettings", "Graph Preset 2"))
        self.graphPreset.setItemText(2, _translate("managerSettings", "Graph Preset 3"))
        self.graphData1.setItemText(0, _translate("managerSettings", "Monthly - RPC\'s"))
        self.graphData1.setItemText(1, _translate("managerSettings", "Monthly - RPC\'s Per Hour"))
        self.graphData1.setItemText(2, _translate("managerSettings", "Monthly - Connects"))
        self.graphData1.setItemText(3, _translate("managerSettings", "Monthly - Connects Per Hour"))
        self.graphData1.setItemText(4, _translate("managerSettings", "Monthly - Conversions"))
        self.graphData1.setItemText(5, _translate("managerSettings", "Monthly - Fees"))
        self.graphData1.setItemText(6, _translate("managerSettings", "Monthly - Totals"))
        self.graphData1.setItemText(7, _translate("managerSettings", "Weekly - RPC\'s"))
        self.graphData1.setItemText(8, _translate("managerSettings", "Weekly - RPC\'s Per Hour"))
        self.graphData1.setItemText(9, _translate("managerSettings", "Weekly - Connects"))
        self.graphData1.setItemText(10, _translate("managerSettings", "Weekly - Connects Per Hour"))
        self.graphData1.setItemText(11, _translate("managerSettings", "Weekly - Conversions"))
        self.graphData1.setItemText(12, _translate("managerSettings", "Weekly - Fees"))
        self.graphData3.setItemText(0, _translate("managerSettings", "Monthly - RPC\'s"))
        self.graphData3.setItemText(1, _translate("managerSettings", "Monthly - RPC\'s Per Hour"))
        self.graphData3.setItemText(2, _translate("managerSettings", "Monthly - Connects"))
        self.graphData3.setItemText(3, _translate("managerSettings", "Monthly - Connects Per Hour"))
        self.graphData3.setItemText(4, _translate("managerSettings", "Monthly - Conversions"))
        self.graphData3.setItemText(5, _translate("managerSettings", "Monthly - Fees"))
        self.graphData3.setItemText(6, _translate("managerSettings", "Monthly - Totals"))
        self.graphData3.setItemText(7, _translate("managerSettings", "Weekly - RPC\'s"))
        self.graphData3.setItemText(8, _translate("managerSettings", "Weekly - RPC\'s Per Hour"))
        self.graphData3.setItemText(9, _translate("managerSettings", "Weekly - Connects"))
        self.graphData3.setItemText(10, _translate("managerSettings", "Weekly - Connects Per Hour"))
        self.graphData3.setItemText(11, _translate("managerSettings", "Weekly - Conversions"))
        self.graphData3.setItemText(12, _translate("managerSettings", "Weekly - Fees"))
        self.graphData2.setItemText(0, _translate("managerSettings", "Monthly - RPC\'s"))
        self.graphData2.setItemText(1, _translate("managerSettings", "Monthly - RPC\'s Per Hour"))
        self.graphData2.setItemText(2, _translate("managerSettings", "Monthly - Connects"))
        self.graphData2.setItemText(3, _translate("managerSettings", "Monthly - Connects Per Hour"))
        self.graphData2.setItemText(4, _translate("managerSettings", "Monthly - Conversions"))
        self.graphData2.setItemText(5, _translate("managerSettings", "Monthly - Fees"))
        self.graphData2.setItemText(6, _translate("managerSettings", "Monthly - Totals"))
        self.graphData2.setItemText(7, _translate("managerSettings", "Weekly - RPC\'s"))
        self.graphData2.setItemText(8, _translate("managerSettings", "Weekly - RPC\'s Per Hour"))
        self.graphData2.setItemText(9, _translate("managerSettings", "Weekly - Connects"))
        self.graphData2.setItemText(10, _translate("managerSettings", "Weekly - Connects Per Hour"))
        self.graphData2.setItemText(11, _translate("managerSettings", "Weekly - Conversions"))
        self.graphData2.setItemText(12, _translate("managerSettings", "Weekly - Fees"))
        self.graphData4.setItemText(0, _translate("managerSettings", "Monthly - RPC\'s"))
        self.graphData4.setItemText(1, _translate("managerSettings", "Monthly - RPC\'s Per Hour"))
        self.graphData4.setItemText(2, _translate("managerSettings", "Monthly - Connects"))
        self.graphData4.setItemText(3, _translate("managerSettings", "Monthly - Connects Per Hour"))
        self.graphData4.setItemText(4, _translate("managerSettings", "Monthly - Conversions"))
        self.graphData4.setItemText(5, _translate("managerSettings", "Monthly - Fees"))
        self.graphData4.setItemText(6, _translate("managerSettings", "Monthly - Totals"))
        self.graphData4.setItemText(7, _translate("managerSettings", "Weekly - RPC\'s"))
        self.graphData4.setItemText(8, _translate("managerSettings", "Weekly - RPC\'s Per Hour"))
        self.graphData4.setItemText(9, _translate("managerSettings", "Weekly - Connects"))
        self.graphData4.setItemText(10, _translate("managerSettings", "Weekly - Connects Per Hour"))
        self.graphData4.setItemText(11, _translate("managerSettings", "Weekly - Conversions"))
        self.graphData4.setItemText(12, _translate("managerSettings", "Weekly - Fees"))
import main_images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    managerSettings = QtWidgets.QDialog()
    ui = Ui_managerSettings()
    ui.setupUi(managerSettings)
    managerSettings.show()
    sys.exit(app.exec_())
