# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Files\schedule_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_scheduleViewer(object):
    def setupUi(self, scheduleViewer):
        scheduleViewer.setObjectName("scheduleViewer")
        scheduleViewer.resize(308, 243)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Ui_Files\\../Meduit_logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        scheduleViewer.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(scheduleViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(scheduleViewer)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.empSchWed = QtWidgets.QCheckBox(self.groupBox_2)
        self.empSchWed.setStyleSheet("QCheckBox[enabled=\"false\"]{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.empSchWed.setChecked(True)
        self.empSchWed.setObjectName("empSchWed")
        self.gridLayout_4.addWidget(self.empSchWed, 3, 1, 1, 1)
        self.schStartWed = QtWidgets.QTimeEdit(self.groupBox_2)
        self.schStartWed.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(7, 0, 0)))
        self.schStartWed.setMaximumTime(QtCore.QTime(9, 0, 0))
        self.schStartWed.setMinimumTime(QtCore.QTime(6, 0, 0))
        self.schStartWed.setObjectName("schStartWed")
        self.gridLayout_4.addWidget(self.schStartWed, 3, 2, 1, 1)
        self.schStartThur = QtWidgets.QTimeEdit(self.groupBox_2)
        self.schStartThur.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(7, 0, 0)))
        self.schStartThur.setMaximumTime(QtCore.QTime(9, 0, 0))
        self.schStartThur.setMinimumTime(QtCore.QTime(6, 0, 0))
        self.schStartThur.setObjectName("schStartThur")
        self.gridLayout_4.addWidget(self.schStartThur, 4, 2, 1, 1)
        self.empSchTue = QtWidgets.QCheckBox(self.groupBox_2)
        self.empSchTue.setStyleSheet("QCheckBox[enabled=\"false\"]{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.empSchTue.setChecked(True)
        self.empSchTue.setObjectName("empSchTue")
        self.gridLayout_4.addWidget(self.empSchTue, 2, 1, 1, 1)
        self.schStartTue = QtWidgets.QTimeEdit(self.groupBox_2)
        self.schStartTue.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(7, 0, 0)))
        self.schStartTue.setMaximumTime(QtCore.QTime(9, 0, 0))
        self.schStartTue.setMinimumTime(QtCore.QTime(6, 0, 0))
        self.schStartTue.setObjectName("schStartTue")
        self.gridLayout_4.addWidget(self.schStartTue, 2, 2, 1, 1)
        self.empSchThur = QtWidgets.QCheckBox(self.groupBox_2)
        self.empSchThur.setStyleSheet("QCheckBox[enabled=\"false\"]{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.empSchThur.setChecked(True)
        self.empSchThur.setObjectName("empSchThur")
        self.gridLayout_4.addWidget(self.empSchThur, 4, 1, 1, 1)
        self.empSchMon = QtWidgets.QCheckBox(self.groupBox_2)
        self.empSchMon.setStyleSheet("QCheckBox[enabled=\"false\"]{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.empSchMon.setChecked(True)
        self.empSchMon.setObjectName("empSchMon")
        self.gridLayout_4.addWidget(self.empSchMon, 1, 1, 1, 1)
        self.schStartMon = QtWidgets.QTimeEdit(self.groupBox_2)
        self.schStartMon.setEnabled(True)
        self.schStartMon.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(7, 0, 0)))
        self.schStartMon.setMaximumTime(QtCore.QTime(9, 0, 0))
        self.schStartMon.setMinimumTime(QtCore.QTime(6, 0, 0))
        self.schStartMon.setObjectName("schStartMon")
        self.gridLayout_4.addWidget(self.schStartMon, 1, 2, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 9, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.quickEdit = QtWidgets.QComboBox(self.frame_6)
        self.quickEdit.setObjectName("quickEdit")
        self.quickEdit.addItem("")
        self.quickEdit.addItem("")
        self.quickEdit.addItem("")
        self.quickEdit.addItem("")
        self.quickEdit.addItem("")
        self.verticalLayout_2.addWidget(self.quickEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_4.addWidget(self.frame_6, 0, 0, 7, 1)
        self.empSchFri = QtWidgets.QCheckBox(self.groupBox_2)
        self.empSchFri.setStyleSheet("QCheckBox[enabled=\"false\"]{\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.empSchFri.setChecked(True)
        self.empSchFri.setObjectName("empSchFri")
        self.gridLayout_4.addWidget(self.empSchFri, 5, 1, 1, 1)
        self.schStartFri = QtWidgets.QTimeEdit(self.groupBox_2)
        self.schStartFri.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(7, 0, 0)))
        self.schStartFri.setMaximumTime(QtCore.QTime(9, 0, 0))
        self.schStartFri.setMinimumTime(QtCore.QTime(6, 0, 0))
        self.schStartFri.setObjectName("schStartFri")
        self.gridLayout_4.addWidget(self.schStartFri, 5, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.frame = QtWidgets.QFrame(scheduleViewer)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(scheduleViewer)
        QtCore.QMetaObject.connectSlotsByName(scheduleViewer)

    def retranslateUi(self, scheduleViewer):
        _translate = QtCore.QCoreApplication.translate
        scheduleViewer.setWindowTitle(_translate("scheduleViewer", "Schedule Viewer"))
        self.groupBox_2.setTitle(_translate("scheduleViewer", "Employee Schedule"))
        self.empSchWed.setText(_translate("scheduleViewer", "Wednesday"))
        self.empSchTue.setText(_translate("scheduleViewer", "Tuesday"))
        self.empSchThur.setText(_translate("scheduleViewer", "Thursday"))
        self.empSchMon.setText(_translate("scheduleViewer", "Monday"))
        self.label_3.setText(_translate("scheduleViewer", "Quick Edit"))
        self.quickEdit.setItemText(0, _translate("scheduleViewer", "7:00"))
        self.quickEdit.setItemText(1, _translate("scheduleViewer", "7:30"))
        self.quickEdit.setItemText(2, _translate("scheduleViewer", "8:00"))
        self.quickEdit.setItemText(3, _translate("scheduleViewer", "8:30"))
        self.quickEdit.setItemText(4, _translate("scheduleViewer", "9:00"))
        self.empSchFri.setText(_translate("scheduleViewer", "Friday"))
        self.saveButton.setText(_translate("scheduleViewer", "Save"))
        self.cancelButton.setText(_translate("scheduleViewer", "Cancel"))
import main_images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    scheduleViewer = QtWidgets.QDialog()
    ui = Ui_scheduleViewer()
    ui.setupUi(scheduleViewer)
    scheduleViewer.show()
    sys.exit(app.exec_())
