# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Files\top_five.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_top5Agents(object):
    def setupUi(self, top5Agents):
        top5Agents.setObjectName("top5Agents")
        top5Agents.resize(522, 293)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"\\172.16.33.31\collectone\COLLECTOR RESOURCES\KPI Tracker\cmredb\Meduit_logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        top5Agents.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(top5Agents)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(top5Agents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("QLabel{\n"
"    font: 75 22pt \"Segoe Print\";\n"
"    text-decoration: underline;\n"
"    background-color: qlineargradient(spread:pad, x1:0.557, y1:0, x2:0.511, y2:1, stop:0.528409 rgba(255, 255, 255, 174));\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.frame = QtWidgets.QFrame(top5Agents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listConvView = QtWidgets.QListView(self.frame)
        self.listConvView.setStyleSheet("QListView{\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}")
        self.listConvView.setObjectName("listConvView")
        self.gridLayout_2.addWidget(self.listConvView, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("QLabel{\n"
"    font: 14pt \"Corbel\";\n"
"    font-weight: bold;\n"
"    background-color: qlineargradient(spread:pad, x1:0.557, y1:0, x2:0.511, y2:1, stop:0.528409 rgba(255, 255, 255, 174));\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.listRPCView = QtWidgets.QListView(self.frame)
        self.listRPCView.setStyleSheet("QListView{\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}")
        self.listRPCView.setObjectName("listRPCView")
        self.gridLayout_2.addWidget(self.listRPCView, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("QLabel{\n"
"    font: 14pt \"Corbel\";\n"
"    font-weight: bold;\n"
"    background-color: qlineargradient(spread:pad, x1:0.557, y1:0, x2:0.511, y2:1, stop:0.528409 rgba(255, 255, 255, 174));\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 3)

        self.retranslateUi(top5Agents)
        QtCore.QMetaObject.connectSlotsByName(top5Agents)

    def retranslateUi(self, top5Agents):
        _translate = QtCore.QCoreApplication.translate
        top5Agents.setWindowTitle(_translate("top5Agents", "Today\'s Top 5"))
        self.label.setText(_translate("top5Agents", "Today\'s Top 5!"))
        self.label_3.setText(_translate("top5Agents", "Conversion Rate"))
        self.label_2.setText(_translate("top5Agents", "RPC\'s Per Hour"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    top5Agents = QtWidgets.QDialog()
    ui = Ui_top5Agents()
    ui.setupUi(top5Agents)
    top5Agents.show()
    sys.exit(app.exec_())
